### ISSUE TITLE
Nie ma kodu

### ISSUE THREAD

**Issue by l0werkey** [real-kijmoshi/gor-ceJad-odajnieWTwojejOkolicy#1]
![297l8kz0ysba1](https://github.com/real-kijmoshi/gor-ceJad-odajnieWTwojejOkolicy/assets/149694615/c17ece7a-bc0e-49b0-be9c-1d143b39d905)

**Comment by real-kijmoshi** [comment]
Trzeba napisać

**Comment by real-kijmoshi** [comment]
Jutro mogę baze nadpisać jakoś rano bo mnie dziś w domu nie ma a w pon na wycieczkę jadę mogę przemycić kompa i trochę kawy to skończę

**Comment by Szymon-Rogalski** [comment]
nareszcie jest kod

**Comment by l0werkey** [comment]
nareszcie coś jest
